spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # The issuer-uri configuration in Spring Boot's security OAuth2 resource server settings specifies the
          # URI of the OpenID Connect Provider (also known as the Authorization Server) that issues the JWT tokens.
          # This is a crucial configuration for JWT validation.
          issuer-uri: http://localhost:9000
management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    auth:
      enabled: true
server:
  port: 8081
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security:
          web: DEBUG