spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          milton-client:
            provider: milton-provider
            client-id: milton-client
            client-secret: milton-secret
            authorization-grant-type: client_credentials
            scope: read
        provider:
          milton-provider:
            token-uri: http://localhost:9000/oauth2/token
server:
  port: 8085
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure: DEBUG